import { json, error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { generatePairingCode } from '$lib/server/pairing';
import { log } from '$lib/server/logger';

export const POST: RequestHandler = async (event) => {
	if (!event.locals.user) {
		error(401, 'Unauthorized');
	}

	const code = generatePairingCode();
	log.pairing.info({ userId: event.locals.user.id }, 'pairing code generated by user');
	return json({ code });
};
